import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import * as fs from 'fs';

const banner = `/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */`;
const prod = (process.argv[2] === "production");

const sqlWasmFile = 'node_modules/sql.js/dist/sql-wasm.wasm';
if (fs.existsSync(sqlWasmFile)) {
    fs.copyFileSync(sqlWasmFile, 'sql-wasm.wasm');
    console.log("Copied sql-wasm.wasm to plugin root.");
}

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [ "obsidian", "electron", ...builtins ],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: `main.js`,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}